image: privacybydesign/node_yarn:latest

stages:
  - build

before_script:
  - set -euxo pipefail
  - apt-get update
  - apt-get install -y --no-install-recommends php php-curl php-xml php-mbstring composer
  - composer install
  - yarn install

build:
  stage: build
  script:
    - set -euxo pipefail
    - ./build.sh
    - mkdir build
    - cp -R ./{css,edugain,js,linkedin,surfnet,twitter,vendor} build
    - cp *.php build
    - rm build/*.sample.php
  artifacts:
    # Disabling artifact expiry is not supported yet, so make
    expire_in: 100 year
    paths:
    - build/*

install-simplesamlphp:
  stage: build
  script:
    - set -euxo pipefail
    - ./install-simplesamlphp.sh
  artifacts:
    # Disabling artifact expiry is not supported yet, so make
    expire_in: 100 year
    paths:
      - simplesamlphp/*
